### ISSUE TITLE
支持禁用 SSL 检查

### ISSUE THREAD

**Issue by yanshiqwq** [ApliNi/AutoUpdatePlugins#5]
在使用 Watt Toolkit 等代理工具代理 Github 等下载源时会报错 PKIX path building failed (即使已安装对应CA证书)
![图片](https://github.com/ApliNi/AutoUpdatePlugins/assets/56720055/f06429ed-c53e-4342-9fb1-3db13bf41011)
希望能加一个禁用 SSL 检查的功能

**Comment by ApliNi** [comment]
久等了, 请试试这个新版本: https://github.com/ApliNi/AutoUpdatePlugins/releases/tag/v2.6.2
