### ISSUE TITLE
any chance for english version?

### ISSUE THREAD

**Issue by vampiregoat699** [ApliNi/AutoUpdatePlugins#8]
Not even sure if this mod is working right as everything is in another language so not sure what if anything it is doing.

**Comment by ApliNi** [comment]
Hey, you can view English documentation and English configuration
- https://github.com/ApliNi/AutoUpdatePlugins/blob/main/README_EN.md
- https://github.com/ApliNi/AutoUpdatePlugins/blob/main/src/main/resources/Locales/config_en.yml
