### ISSUE TITLE
How to update premium add-on's?

### ISSUE THREAD

**Issue by SanwebGit** [ApliNi/AutoUpdatePlugins#9]
First, thank you for your work and time to provide us with this great plugin.

I would like to ask if there is a way to automatically update purchased premium plugins via spigotmc.org ...

Best regards

**Comment by ApliNi** [comment]
This problem may not be solved, mainly because I have not looked into paid plugins and have not found a solution. I may look into it later (much later), but why not ask the developers of paid plugins to provide automatic update function?
